### ISSUE TITLE
Need Language Localisation

### ISSUE THREAD

**Issue by RakhimyanTim** [anicdh/date_range_picker#21]
Hi! Thank you for your Time. How I can set it in different language? (for ex. ru-RU).

**Comment by Akuma686** [comment]
> Hi! Thank you for your Time. How I can set it in different language? (for ex. ru-RU).

Try to setup localization https://flutter.dev/docs/development/accessibility-and-localization/internationalization

![image](https://user-images.githubusercontent.com/12208952/61846871-f77c6280-aed2-11e9-8f44-49f2814bb790.png)

**Comment by xhidnoda** [comment]
> > Hi! Thank you for your Time. How I can set it in different language? (for ex. ru-RU).
> 
> Try to setup localization https://flutter.dev/docs/development/accessibility-and-localization/internationalization
> 
> ![image](https://user-images.githubusercontent.com/12208952/61846871-f77c6280-aed2-11e9-8f44-49f2814bb790.png)

Can you explain step by step how you dit?

**Comment by Akuma686** [comment]
To use flutter_localizations, add the package as a dependency to your pubspec.yaml file:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1



Next, import the flutter_localizations library and specify localizationsDelegates and supportedLocales for MaterialApp(main.dart):

import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_cupertino_localizations/flutter_cupertino_localizations.dart';

MaterialApp(
 localizationsDelegates: [
   // ... app-specific localization delegate[s] here
   GlobalMaterialLocalizations.delegate,
   GlobalWidgetsLocalizations.delegate,
   GlobalCupertinoLocalizations.delegate,
 ],
 supportedLocales: [
    const Locale('ru'), // Russian
  ],
  // ...
)

**Comment by xhidnoda** [comment]
> To use flutter_localizations, add the package as a dependency to your pubspec.yaml file:
> 
> dependencies:
> flutter:
> sdk: flutter
> flutter_localizations:
> sdk: flutter
> flutter_cupertino_localizations: ^1.0.1
> 
> Next, import the flutter_localizations library and specify localizationsDelegates and supportedLocales for MaterialApp(main.dart):
> 
> import 'package:flutter_localizations/flutter_localizations.dart';
> import 'package:flutter_cupertino_localizations/flutter_cupertino_localizations.dart';
> 
> MaterialApp(
> localizationsDelegates: [
> // ... app-specific localization delegate[s] here
> GlobalMaterialLocalizations.delegate,
> GlobalWidgetsLocalizations.delegate,
> GlobalCupertinoLocalizations.delegate,
> ],
> supportedLocales: [
> const Locale('ru'), // Russian
> ],
> // ...
> )

Thanks @Akuma686 , but one more question: This flutter_localizations method only works when the Device has set the language, for example 'ru'? so the library show in 'ru'? what happen if the Device has a 'us' language and i want to show the library in 'ru' language?

**Comment by RakhimyanTim** [comment]
@Akuma686 Thank you a lot. It's working!
