### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by NemanjaLugi** [anicdh/date_range_picker#3]
Hi, I have a design problem in Landscape mode, is there an update for this?

![img_0333](https://user-images.githubusercontent.com/24244215/47720925-4f8d7d80-dc4f-11e8-96a9-5e7c7806ce42.jpg)

**Comment by andoanwkm** [comment]
Yeah, I will check it and update. Thanks for your report! 👍

**Comment by anicdh** [comment]
<img width="445" alt="screen shot 2018-11-04 at 4 31 34 pm" src="https://user-images.githubusercontent.com/14521405/47962501-18084200-e050-11e8-809d-d2d1843811aa.png">
I fixed it on version 1.0.3. Thanks for your report!
