### ISSUE TITLE
List<DateTime> returns a null object if only one date is selected

### ISSUE THREAD

**Issue by juanchazo** [anicdh/date_range_picker#4]
I've run into an issue where if the `DateRangePicker` returns with only one date selected, the `List<DateTime>` returned will be of `length == 2` but only the first item will be a valid `DateTime` object while the second item is `null`, which is very misleading if I'm using the length of the `List<DateTime>` to verify that the user has selected a date range rather than a single date.

**Comment by anicdh** [comment]
@juanchazo I fixed it in version 1.0.4. Sorry for the late response and thank you about the report 👍
