### ISSUE TITLE
Null Safety Support ?

### ISSUE THREAD

**Issue by ufukhawk** [anicdh/date_range_picker#49]
When will Null-Safety support come?

**Comment by momtboy** [comment]
same question!

**Comment by faisalmushtaq007** [comment]
same question, 
and is anybody looking after this repo????

**Comment by anicdh** [comment]
Currently I'm stop to develop this project. But any PRs are welcome!

**Comment by gagan-garcha** [comment]
I have migrated the package to null safety. Plzz have a look.

**Comment by anicdh** [comment]
I've merged the PR. Thanks for your contribution @gagan-garcha :+1:

**Comment by kmochimaru** [comment]
I used https://api.flutter.dev/flutter/material/showDateRangePicker.html

**Comment by kmochimaru** [comment]
> When will Null-Safety support come?
I used https://api.flutter.dev/flutter/material/showDateRangePicker.html
