### ISSUE TITLE
Screen adaptation problem

### ISSUE THREAD

**Issue by gaojuanjuan** [anicdh/date_range_picker#6]
![image](https://user-images.githubusercontent.com/14133759/49208032-9c50a980-f3f1-11e8-9dd5-2d07bb2cb90a.png)
Screen adaptation problem

**Comment by ValeryNomenjanahary** [comment]
Same error mentionned above

**Comment by jkyeo** [comment]
Same here.

**Comment by anicdh** [comment]
I fixed it, please help me check 👍

**Comment by jkyeo** [comment]
> I fixed it, please help me check 👍

It work here.👍


---
device: Pixel 2 XL running Android 9
