### ISSUE TITLE
Click OK and Cancel button did not respond

### ISSUE THREAD

**Issue by gaojuanjuan** [anicdh/date_range_picker#7]

**Comment by anicdh** [comment]
I've updated new version `1.0.5` related to this issue. Can you help me test again? Thanks!!!

**Comment by mrmikezhang** [comment]
I have got the exact issue, seems like the latest flutter update has broken this package. My current setup is:
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.29.1)
[√] VS Code, 32-bit edition
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (1 available)

Besides the Cancel and OK buttons not responding, I am also getting the error below when trying to click outside the calendar: 

Could not load source 'dart:core/runtime/liberrors_patch.dart': <source not available>.

Any help would be appreciated, thank you.

**Comment by mrmikezhang** [comment]
False alarm, for anyone experiencing the same problem. You need to restart your IDE (VS code in my case) and run flutter -clean, before you rebuild the app and then it should work again.
